const thin={style:'thin',color:{argb:'FF808080'}}, medium={style:'medium',color:{argb:'FF555555'}}, doubleBorder={style:'double',color:{argb:'FF555555'}};
const yellow='FFFFFF99', totalBlue='FFB7DEE8', subtotalOrange='FFFCD5B4', white='FFFFFFFF';
function allBorders(range){ range.eachCell({includeEmpty:true},cell=>{cell.border={top:thin,left:thin,bottom:thin,right:thin};}); }
function moneyFmt(cell){ cell.numFmt='#,##0;[Red]-#,##0;-'; cell.alignment={horizontal:'right',vertical:'middle'}; }
function titleStyle(cell){ cell.font={name:'맑은 고딕',size:20,bold:true}; cell.alignment={horizontal:'center',vertical:'middle'}; }
function headerFill(cell,color=yellow){ cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:color}}; cell.font={name:'맑은 고딕',size:12,bold:true}; cell.alignment={horizontal:'center',vertical:'middle',wrapText:true}; }
function setOuterMedium(ws,startRow,endRow,startCol,endCol){
  for(let c=startCol;c<=endCol;c++){ ws.getCell(startRow,c).border={...(ws.getCell(startRow,c).border||{}),top:medium}; ws.getCell(endRow,c).border={...(ws.getCell(endRow,c).border||{}),bottom:medium}; }
  for(let r=startRow;r<=endRow;r++){ ws.getCell(r,startCol).border={...(ws.getCell(r,startCol).border||{}),left:medium}; ws.getCell(r,endCol).border={...(ws.getCell(r,endCol).border||{}),right:medium}; }
}
function setupBook(){ const wb=new ExcelJS.Workbook(); wb.creator='딸깍 실적공개'; wb.created=new Date(); return wb; }
function sheetDate(d){ return d ? new Date(d.getFullYear(),d.getMonth(),d.getDate()) : ''; }
function reportFileName(title){ return title.replace(/[\\/:*?"<>|]/g,'').trim()+'.xlsx'; }

async function buildExpenseWorkbook(){
  const list=filtered(state.expense).filter(x=>!x.excluded).slice().sort((a,b)=>EXPENSE_GROUPS.indexOf(a.category)-EXPENSE_GROUPS.indexOf(b.category)||sortDate(a,b));
  const wb=setupBook(), ws=wb.addWorksheet('업무추진비 월별 집행내역',{views:[{showGridLines:false}]}); ws.properties.defaultRowHeight=21;
  ws.columns=[8.38,12.88,45.63,17.63,13.63,10.13,8.38].map(width=>({width}));
  const period=reportPeriodLabel(list); const title=`업무추진비 집행내역${period?` (${period})`:''}`; ws.mergeCells('A1:G1'); ws.getCell('A1').value=title; titleStyle(ws.getCell('A1'));
  ws.getCell('A3').value='▣ 내역별 현황'; ws.getCell('A3').font={size:14,bold:true}; ws.getCell('G3').value='[금액단위 : 원]'; ws.getCell('G3').font={size:11,bold:true}; ws.getCell('G3').alignment={horizontal:'right'};
  for(let r=4;r<=10;r++){ws.mergeCells(`A${r}:B${r}`);ws.mergeCells(`F${r}:G${r}`);} ws.mergeCells('D4:E4');
  ['구     분','건  수','금   액','구성비(%)'].forEach((v,i)=>ws.getCell(4,[1,3,4,6][i]).value=v);
  for(let c=1;c<=7;c++) headerFill(ws.getCell(4,c));
  const gp=grouped(list,EXPENSE_GROUPS), totalAmount=list.reduce((s,x)=>s+x.amount,0);
  EXPENSE_GROUPS.forEach((g,i)=>{ const r=5+i,a=gp.get(g),amt=a.reduce((s,x)=>s+x.amount,0); ws.getCell(r,1).value=g;ws.getCell(r,3).value=a.length?`${a.length}건`:'건';ws.getCell(r,5).value=a.length?amt:null;if(a.length)moneyFmt(ws.getCell(r,5));ws.getCell(r,6).value=totalAmount?amt/totalAmount:0;ws.getCell(r,6).numFmt='0.0%';ws.getCell(r,6).alignment={horizontal:'center'}; });
  ws.getCell('A10').value='합    계';ws.getCell('C10').value=`${list.length}건`;ws.getCell('E10').value=totalAmount;moneyFmt(ws.getCell('E10'));ws.getCell('F10').value=list.length?1:0;ws.getCell('F10').numFmt='0.0%'; for(let c=1;c<=7;c++){ws.getCell(10,c).fill={type:'pattern',pattern:'solid',fgColor:{argb:totalBlue}};ws.getCell(10,c).font={bold:true};}
  allBorders(ws.getRange?ws.getRange('A4:G10'):{eachCell:()=>{}}); // harmless fallback for browser ExcelJS variants
  for(let r=4;r<=10;r++)for(let c=1;c<=7;c++){const cell=ws.getCell(r,c);cell.font={...(cell.font||{}),name:'맑은 고딕',size:12,bold:true};cell.alignment={...(cell.alignment||{}),horizontal:cell.alignment?.horizontal||'center',vertical:'middle'};cell.border={top:thin,left:thin,bottom:thin,right:thin};}
  setOuterMedium(ws,4,10,1,7); for(let c=1;c<=7;c++) ws.getCell(4,c).border={...(ws.getCell(4,c).border||{}),bottom:doubleBorder};
  // 내역별 현황의 금액 영역(D:E)은 하나의 시각적 영역처럼 보이도록 가운데 세로선을 없앱니다.
  for(let r=5;r<=10;r++){
    const d=ws.getCell(r,4), e=ws.getCell(r,5);
    const {right: _dr, ...db}=d.border||{}; d.border=db;
    const {left: _el, ...eb}=e.border||{}; e.border=eb;
  }
  ws.getCell('A12').value='▣ 세부 집행내역';ws.getCell('A12').font={size:14,bold:true};ws.getCell('G12').value='[금액단위 : 원]';ws.getCell('G12').font={size:11,bold:true};ws.getCell('G12').alignment={horizontal:'right'};
  ['구 분','집행일자','세부내역','집행대상자','장소','집행금액','결재방법'].forEach((v,i)=>{ws.getCell(13,i+1).value=v;headerFill(ws.getCell(13,i+1),'FFFFFF00');});
  let row=14; const detailMergeRanges=[];
  for(const g of EXPENSE_GROUPS){ const arr=gp.get(g); if(!arr.length)continue; const start=row; let amt=0; for(const x of arr){ ws.getCell(row,1).value=g;ws.getCell(row,2).value=sheetDate(x.date);ws.getCell(row,2).numFmt='yyyy-mm-dd';ws.getCell(row,3).value=publicText(x.detail,x);ws.getCell(row,4).value=publicText(x.target,x);ws.getCell(row,5).value=publicVendor(x);ws.getCell(row,6).value=x.amount;moneyFmt(ws.getCell(row,6));ws.getCell(row,7).value=x.payment; for(let c=1;c<=7;c++){ws.getCell(row,c).border={top:thin,left:thin,bottom:thin,right:thin};ws.getCell(row,c).alignment={...(ws.getCell(row,c).alignment||{}),vertical:'middle',horizontal:c===6?'right':'center',wrapText:c===1};}
    ws.getCell(row,3).alignment={vertical:'middle',horizontal:'left',shrinkToFit:true,wrapText:false};
    amt+=x.amount;row++; } const end=row-1; ws.getCell(row,2).value='소계';ws.getCell(row,3).value=`${arr.length}건`;ws.getCell(row,6).value=amt;moneyFmt(ws.getCell(row,6));for(let c=2;c<=7;c++){ws.getCell(row,c).fill={type:'pattern',pattern:'solid',fgColor:{argb:subtotalOrange}};ws.getCell(row,c).font={bold:true};}for(let c=1;c<=7;c++)ws.getCell(row,c).border={top:thin,left:thin,bottom:thin,right:thin}; if(row>start)ws.mergeCells(start,1,row,1); row++; }
  ws.mergeCells(row,1,row,2);ws.getCell(row,1).value='총 계';ws.getCell(row,3).value=`${list.length}건`;ws.getCell(row,6).value=totalAmount;moneyFmt(ws.getCell(row,6));for(let c=1;c<=7;c++){ws.getCell(row,c).fill={type:'pattern',pattern:'solid',fgColor:{argb:totalBlue}};ws.getCell(row,c).font={bold:true};ws.getCell(row,c).border={top:thin,left:thin,bottom:thin,right:thin};} setOuterMedium(ws,13,row,1,7);
  return {buffer:await wb.xlsx.writeBuffer(),title,fileName:reportFileName(title)};
}

async function buildCardWorkbook(){
  const list=filtered(state.card).slice().sort((a,b)=>CARD_GROUPS.indexOf(a.category)-CARD_GROUPS.indexOf(b.category)||sortDate(a,b)); const wb=setupBook(),ws=wb.addWorksheet('법인카드 사용내역',{views:[{showGridLines:false}]}); ws.properties.defaultRowHeight=21; ws.columns=[12.67,10.67,30.11,11.78,13.11,7.22].map(width=>({width}));
  const period=reportPeriodLabel(list); const title=`법인카드 사용내역${period?` (${period})`:''}`;ws.mergeCells('A1:F1');ws.getCell('A1').value=title;titleStyle(ws.getCell('A1'));ws.getCell('A3').value='▣ 공개대상 : 업무추진비(50만원 이상) 기타(100만원 이상)';ws.getCell('A3').font={size:14,bold:true};ws.getCell('A4').value='▣ 내역별 현황';ws.getCell('A4').font={size:14,bold:true};ws.getCell('F4').value='[금액단위 : 원]';ws.getCell('F4').font={size:11,bold:true};ws.getCell('F4').alignment={horizontal:'right'};
  for(let r=5;r<=8;r++)ws.mergeCells(r,1,r,3); ['구     분','건  수','금   액','비고'].forEach((v,i)=>ws.getCell(5,[1,4,5,6][i]).value=v); for(let c=1;c<=6;c++)headerFill(ws.getCell(5,c));
  const gp=grouped(list,CARD_GROUPS), total=list.reduce((s,x)=>s+x.amount,0); CARD_GROUPS.forEach((g,i)=>{const r=6+i,a=gp.get(g),amt=a.reduce((s,x)=>s+x.amount,0);ws.getCell(r,1).value=g;ws.getCell(r,4).value=a.length?`${a.length}건`:'건';ws.getCell(r,5).value=a.length?amt:null;if(a.length)moneyFmt(ws.getCell(r,5));});ws.getCell('A8').value='합    계';ws.getCell('D8').value=`${list.length}건`;ws.getCell('E8').value=total;moneyFmt(ws.getCell('E8'));for(let r=5;r<=8;r++)for(let c=1;c<=6;c++){ws.getCell(r,c).border={top:thin,left:thin,bottom:thin,right:thin};ws.getCell(r,c).font={...(ws.getCell(r,c).font||{}),bold:true};ws.getCell(r,c).alignment={...(ws.getCell(r,c).alignment||{}),horizontal:ws.getCell(r,c).alignment?.horizontal||'center',vertical:'middle'};}for(let c=1;c<=6;c++)ws.getCell(8,c).fill={type:'pattern',pattern:'solid',fgColor:{argb:totalBlue}};setOuterMedium(ws,5,8,1,6);
  ws.getCell('A10').value='▣ 세부 집행내역';ws.getCell('A10').font={size:14,bold:true};ws.getCell('F10').value='[금액단위 : 원]';ws.getCell('F10').font={size:11,bold:true};ws.getCell('F10').alignment={horizontal:'right'};ws.mergeCells('C11:D11');['구 분','사용일자','사용내역','금  액','비고'].forEach((v,i)=>ws.getCell(11,[1,2,3,5,6][i]).value=v);for(let c=1;c<=6;c++)headerFill(ws.getCell(11,c),'FFFFFF00');
  let row=12;for(const g of CARD_GROUPS){const arr=gp.get(g);if(!arr.length)continue;const start=row;let amt=0;for(const x of arr){ws.getCell(row,1).value=g;ws.getCell(row,1).font={size:9};ws.getCell(row,2).value=sheetDate(x.date);ws.getCell(row,2).numFmt='yyyy-mm-dd';ws.mergeCells(row,3,row,4);ws.getCell(row,3).value=x.detail;ws.getCell(row,5).value=x.amount;moneyFmt(ws.getCell(row,5));for(let c=1;c<=6;c++){ws.getCell(row,c).border={top:thin,left:thin,bottom:thin,right:thin};ws.getCell(row,c).alignment={...(ws.getCell(row,c).alignment||{}),vertical:'middle',horizontal:c===5?'right':'center',wrapText:c===1};}
    ws.getCell(row,3).alignment={vertical:'middle',horizontal:'left',shrinkToFit:true,wrapText:false};
    amt+=x.amount;row++;}const end=row-1;ws.getCell(row,2).value='소계';ws.mergeCells(row,3,row,4);ws.getCell(row,3).value=`${arr.length}건`;ws.getCell(row,5).value=amt;moneyFmt(ws.getCell(row,5));for(let c=2;c<=6;c++){ws.getCell(row,c).fill={type:'pattern',pattern:'solid',fgColor:{argb:subtotalOrange}};ws.getCell(row,c).font={bold:true};}for(let c=1;c<=6;c++)ws.getCell(row,c).border={top:thin,left:thin,bottom:thin,right:thin};if(row>start)ws.mergeCells(start,1,row,1);row++;}
  ws.mergeCells(row,1,row,2);ws.getCell(row,1).value='총 계';ws.mergeCells(row,3,row,4);ws.getCell(row,3).value=`${list.length}건`;ws.getCell(row,5).value=total;moneyFmt(ws.getCell(row,5));for(let c=1;c<=6;c++){ws.getCell(row,c).fill={type:'pattern',pattern:'solid',fgColor:{argb:totalBlue}};ws.getCell(row,c).font={bold:true};ws.getCell(row,c).border={top:thin,left:thin,bottom:thin,right:thin};}setOuterMedium(ws,11,row,1,6);return {buffer:await wb.xlsx.writeBuffer(),title,fileName:reportFileName(title)};
}

async function buildGiftWorkbook(){
  const list=filtered(state.gift);if(!list.length)return null;const wb=setupBook(),ws=wb.addWorksheet('상품권 사용내역',{views:[{showGridLines:false}]});ws.properties.defaultRowHeight=21;ws.columns=[12,35,15,12,20,20,10].map(width=>({width}));const period=reportPeriodLabel(list); const title=`상품권 구매 및 사용내역${period?` (${period})`:''}`;ws.mergeCells('A1:G1');ws.getCell('A1').value=title;titleStyle(ws.getCell('A1'));ws.getCell('A3').value='▣ 세부 집행내역';ws.getCell('A3').font={size:14,bold:true};ws.getCell('G3').value='[금액단위 : 원]';ws.getCell('G3').font={size:11,bold:true};ws.getCell('G3').alignment={horizontal:'right'};['구매일자','구매(사용)용도','구매처','총구매수량','총구매금액(할인전)','결제금액(할인후)','할인율'].forEach((v,i)=>{ws.getCell(4,i+1).value=v;headerFill(ws.getCell(4,i+1),'FFFFFF00');});let row=5,totalQty=0,totalFace=0,totalPaid=0;for(const x of list){const d=giftDerived(x);ws.getCell(row,1).value=sheetDate(x.date);ws.getCell(row,1).numFmt='yyyy-mm-dd';ws.getCell(row,2).value=x.detail;ws.getCell(row,3).value=x.vendor;ws.getCell(row,4).value=Number(x.quantity)||0;ws.getCell(row,5).value=d.face;ws.getCell(row,6).value=x.amount;ws.getCell(row,7).value=d.rate;for(let c=1;c<=7;c++){ws.getCell(row,c).border={top:thin,left:thin,bottom:thin,right:thin};ws.getCell(row,c).alignment={vertical:'middle',horizontal:[4,5,6,7].includes(c)?'right':'center'};}
    ws.getCell(row,2).alignment={vertical:'middle',horizontal:'left',shrinkToFit:true,wrapText:false};
    moneyFmt(ws.getCell(row,4));moneyFmt(ws.getCell(row,5));moneyFmt(ws.getCell(row,6));ws.getCell(row,7).numFmt='0.00%';totalQty+=Number(x.quantity)||0;totalFace+=d.face;totalPaid+=x.amount;row++;}ws.mergeCells(row,1,row,3);ws.getCell(row,1).value='합 계';ws.getCell(row,4).value=totalQty;ws.getCell(row,5).value=totalFace;ws.getCell(row,6).value=totalPaid;for(let c=1;c<=7;c++){ws.getCell(row,c).fill={type:'pattern',pattern:'solid',fgColor:{argb:totalBlue}};ws.getCell(row,c).font={bold:true};ws.getCell(row,c).border={top:thin,left:thin,bottom:thin,right:thin};}moneyFmt(ws.getCell(row,4));moneyFmt(ws.getCell(row,5));moneyFmt(ws.getCell(row,6));setOuterMedium(ws,4,row,1,7);return {buffer:await wb.xlsx.writeBuffer(),title,fileName:reportFileName(title)};
}

function saveBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},500);}
async function buildByType(type){if(!window.ExcelJS)throw new Error('ExcelJS 라이브러리를 불러오지 못했습니다.');if(type==='expense')return buildExpenseWorkbook();if(type==='card')return buildCardWorkbook();return buildGiftWorkbook();}
async function downloadOne(type){try{const r=await buildByType(type);if(!r){toast('상품권 내역이 없어 보고서를 만들지 않았습니다.');return;}saveBlob(new Blob([r.buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),r.fileName);toast('보고서를 생성했습니다.');}catch(e){console.error(e);alert('보고서 생성 중 오류가 발생했습니다.\n'+e.message);}}
async function downloadAll(){try{if(!window.JSZip||!window.ExcelJS)throw new Error('다운로드 라이브러리를 불러오지 못했습니다.');const zip=new JSZip();for(const type of ['expense','card','gift']){const r=await buildByType(type);if(r)zip.file(r.fileName,r.buffer);}const blob=await zip.generateAsync({type:'blob'});saveBlob(blob,`실적공개_보고서_${reportPeriodKey([...state.expense,...state.card,...state.gift])}.zip`);toast('전체 보고서를 ZIP으로 생성했습니다.');}catch(e){console.error(e);alert('ZIP 생성 중 오류가 발생했습니다.\n'+e.message);}}

